In [17]:
import os
import numpy as np
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset
import torch
import torch.nn as nn
import torch.optim as optim

In [18]:
# 데이터 경로 설정
base_dir = "C:/Users/Admin/모션저장2"
categories = ["back", "squat", "side"]

In [19]:
def load_data(base_dir, categories, seq_len=120): 
    """
    데이터 로드 및 크기 조정 (패딩 또는 잘라내기).
    Args:
        base_dir (str): 데이터가 저장된 기본 경로. 
        categories (list): 행동 카테고리 리스트.
        seq_len (int): 고정된 시퀀스 길이.
    Returns:
        np.array: 데이터 배열.
        np.array: 라벨 배열. 
    """
    data = []
    labels = []
    label_map = {category: idx for idx, category in enumerate(categories)}  # 라벨 매핑

    for category in categories:
        category_path = os.path.join(base_dir, category, "좌표")
        print(f"Checking files in: {category_path}")
        for i in range(1, 11):  # keypoints_1 ~ keypoints_10
            file_path = os.path.join(category_path, f"keypoints_{i}.npy")
            if os.path.exists(file_path):
                keypoints = np.load(file_path)  # 데이터 로드
                if keypoints.shape[0] > seq_len:  # 길이가 seq_len보다 길면 잘라내기
                    keypoints = keypoints[:seq_len]
                elif keypoints.shape[0] < seq_len:  # 길이가 seq_len보다 짧으면 패딩
                    pad_width = seq_len - keypoints.shape[0]
                    keypoints = np.pad(keypoints, ((0, pad_width), (0, 0), (0, 0)), mode='constant')
                data.append(keypoints)
                labels.append(label_map[category])
            else:
                print(f"File not found: {file_path}")

    return np.array(data), np.array(labels)

# 수정된 데이터 로드 실행
data, labels = load_data(base_dir, categories)
print(f"Data shape: {data.shape}, Labels shape: {labels.shape}")

Checking files in: C:/Users/Admin/모션저장2\back\좌표
Checking files in: C:/Users/Admin/모션저장2\squat\좌표
Checking files in: C:/Users/Admin/모션저장2\side\좌표
Data shape: (30, 120, 33, 3), Labels shape: (30,)


In [20]:
# 데이터 로드
data, labels = load_data(base_dir, categories)
print(f"Data shape: {data.shape}, Labels shape: {labels.shape}")

Checking files in: C:/Users/Admin/모션저장2\back\좌표
Checking files in: C:/Users/Admin/모션저장2\squat\좌표
Checking files in: C:/Users/Admin/모션저장2\side\좌표
Data shape: (30, 120, 33, 3), Labels shape: (30,)


In [21]:
import os
import numpy as np 

# 데이터 경로 및 라벨 매핑
data_paths = {
    "등": "C:/Users/Admin/모션저장2/back/좌표",
    "스쿼트": "C:/Users/Admin/모션저장2/squat/좌표",
    "옆구리": "C:/Users/Admin/모션저장2/side/좌표"
}
labels_map = {"등": 0, "스쿼트": 1, "옆구리": 2}  # 라벨 매핑

def load_data(data_paths, labels_map, seq_len=120):
    """
    데이터 로드 및 크기 조정 (패딩 또는 잘라내기).
    Args:
        data_paths (dict): 카테고리별 데이터 경로. 
        labels_map (dict): 카테고리와 라벨 매핑.
        seq_len (int): 고정된 시퀀스 길이.
    Returns:
        np.array: 데이터 배열.
        np.array: 라벨 배열.
    """
    data = []
    labels = []
    for category, path in data_paths.items():
        print(f"Checking files in: {path}")
        for i in range(1, 51):  # keypoints_1 ~ keypoints_50
            file_path = os.path.join(path, f"keypoints_{i}.npy")
            if os.path.exists(file_path):
                keypoints = np.load(file_path)  # 데이터 로드
                if keypoints.shape[0] > seq_len:  # 길이가 seq_len보다 길면 잘라내기
                    keypoints = keypoints[:seq_len]
                elif keypoints.shape[0] < seq_len:  # 길이가 seq_len보다 짧으면 패딩
                    pad_width = seq_len - keypoints.shape[0]
                    keypoints = np.pad(keypoints, ((0, pad_width), (0, 0), (0, 0)), mode='constant')
                data.append(keypoints)
                labels.append(labels_map[category])
            else:
                print(f"File not found: {file_path}")
    return np.array(data), np.array(labels)

In [22]:
import os

for label_name, path in data_paths.items():
    print(f"Checking files in: {path}") 
    print(os.listdir(path))

Checking files in: C:/Users/Admin/모션저장2/back/좌표
['keypoints_1.npy', 'keypoints_10.npy', 'keypoints_11.npy', 'keypoints_12.npy', 'keypoints_13.npy', 'keypoints_14.npy', 'keypoints_15.npy', 'keypoints_16.npy', 'keypoints_17.npy', 'keypoints_18.npy', 'keypoints_19.npy', 'keypoints_2.npy', 'keypoints_20.npy', 'keypoints_21.npy', 'keypoints_22.npy', 'keypoints_23.npy', 'keypoints_24.npy', 'keypoints_25.npy', 'keypoints_26.npy', 'keypoints_27.npy', 'keypoints_28.npy', 'keypoints_29.npy', 'keypoints_3.npy', 'keypoints_30.npy', 'keypoints_31.npy', 'keypoints_32.npy', 'keypoints_33.npy', 'keypoints_34.npy', 'keypoints_35.npy', 'keypoints_36.npy', 'keypoints_37.npy', 'keypoints_38.npy', 'keypoints_39.npy', 'keypoints_4.npy', 'keypoints_40.npy', 'keypoints_41.npy', 'keypoints_42.npy', 'keypoints_43.npy', 'keypoints_44.npy', 'keypoints_45.npy', 'keypoints_46.npy', 'keypoints_47.npy', 'keypoints_48.npy', 'keypoints_49.npy', 'keypoints_5.npy', 'keypoints_50.npy', 'keypoints_6.npy', 'keypoints_7.npy'

In [37]:
# 데이터 로드
X, y = load_data(data_paths, labels_map)
print(X)
print(X.shape)

Checking files in: C:/Users/Admin/모션저장2/back/좌표
Checking files in: C:/Users/Admin/모션저장2/squat/좌표
Checking files in: C:/Users/Admin/모션저장2/side/좌표
[[[[ 0.53210479  0.23766159 -0.04846888]
   [ 0.53927219  0.22535481 -0.022795  ]
   [ 0.54356146  0.22484818 -0.02283397]
   ...
   [ 0.48624438  0.89206284  0.09539033]
   [ 0.57258195  0.92519605 -0.07421221]
   [ 0.47435489  0.9266395  -0.06680079]]

  [[ 0.53219205  0.23639371 -0.05077719]
   [ 0.53941137  0.22371404 -0.02500029]
   [ 0.54369193  0.22327204 -0.02504037]
   ...
   [ 0.48616475  0.89190811  0.10693938]
   [ 0.57257152  0.92496645 -0.06710713]
   [ 0.47437444  0.92663968 -0.05707625]]

  [[ 0.53241408  0.23579125 -0.05364032]
   [ 0.53964788  0.22327    -0.02760616]
   [ 0.54390079  0.22292353 -0.02764676]
   ...
   [ 0.48625618  0.89154547  0.09885026]
   [ 0.57250458  0.92483824 -0.06880547]
   [ 0.47446737  0.92660344 -0.06521016]]

  ...

  [[ 0.52958912  0.23433276 -0.0485901 ]
   [ 0.53667951  0.22208185 -0.02492371]
 

In [24]:
# 데이터 크기 확인
print("데이터 크기:", X.shape, y.shape)  # Expected output: (30, frames, joints, coords), (30,)

데이터 크기: (30, 120, 33, 3) (30,)


In [25]:
# 정규화 함수 정의
def normalize_data(data):
    """
    데이터 정규화 (0~1 범위로 스케일링).
    Args:
        data (np.array): 로드된 데이터, Shape: (samples, frames, joints, coords).
    Returns:
        np.array: 정규화된 데이터.
    """
    data_min = data.min(axis=(1, 2, 3), keepdims=True)  # 각 샘플별 최소값
    data_max = data.max(axis=(1, 2, 3), keepdims=True)  # 각 샘플별 최대값
    normalized_data = (data - data_min) / (data_max - data_min + 1e-8)  # 0~1로 스케일링
    return normalized_data

In [26]:
# 데이터 정규화 
X_normalized = normalize_data(X)

In [27]:
# 데이터 분할 (훈련/검증/테스트 세트)
X_train, X_temp, y_train, y_temp = train_test_split(X_normalized, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"Train shape: {X_train.shape}, Validation shape: {X_val.shape}, Test shape: {X_test.shape}")

Train shape: (21, 120, 33, 3), Validation shape: (4, 120, 33, 3), Test shape: (5, 120, 33, 3)


In [28]:
print(X_train.shape)


(21, 120, 33, 3)


In [29]:
# LSTM 모델 정의
class LSTMModel(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers=2):
        super(LSTMModel, self).__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        out, _ = self.lstm(x)  # LSTM 출력
        out = self.fc(out[:, -1, :])  # 마지막 타임스텝의 출력만 사용
        return out 

In [30]:
# 모델 초기화
input_dim = X_train.shape[2] * X_train.shape[3]  # 관절 수 * 좌표 수
hidden_dim = 128
output_dim = len(labels_map)  # 클래스 수 (등, 스쿼트, 옆구리) 
model = LSTMModel(input_dim=input_dim, hidden_dim=hidden_dim, output_dim=output_dim)   

In [31]:
# 데이터 로더 생성
train_dataset = TensorDataset(torch.tensor(X_train).float(), torch.tensor(y_train).long())
val_dataset = TensorDataset(torch.tensor(X_val).float(), torch.tensor(y_val).long())
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=4) 

In [32]:
from sklearn.model_selection import ParameterGrid
from sklearn.metrics import classification_report, confusion_matrix

# 하이퍼파라미터 그리드 정의
param_grid = {
    'hidden_dim': [64, 128, 256],  # 시도할 hidden_dim 값
    'lr': np.arange(0.001, 0.01 + 0.001, 0.001).tolist() # 학습률
} 
grid = ParameterGrid(param_grid)

# 최적의 하이퍼파라미터 저장
best_params = None
best_val_loss = float('inf')

for params in grid:
    hidden_dim = params['hidden_dim']
    lr = params['lr']

    # 모델 초기화
    model = LSTMModel(input_dim=input_dim, hidden_dim=hidden_dim, output_dim=output_dim)

    # 데이터 로더 생성 (기존과 동일)
    train_dataset = TensorDataset(torch.tensor(X_train).float(), torch.tensor(y_train).long())
    val_dataset = TensorDataset(torch.tensor(X_val).float(), torch.tensor(y_val).long())
    train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=4)

    # 손실 함수 및 옵티마이저
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    # 학습 루프
    num_epochs = 75
    for epoch in range(num_epochs):
        model.train()
        train_loss = 0
        for X_batch, y_batch in train_loader:
            optimizer.zero_grad()
            X_batch = X_batch.view(X_batch.size(0), -1, input_dim)  # 차원 변환
            y_pred = model(X_batch)
            loss = criterion(y_pred, y_batch)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        # 검증 단계
        model.eval()
        val_loss = 0
        with torch.no_grad():
            for X_batch, y_batch in val_loader:
                X_batch = X_batch.view(X_batch.size(0), -1, input_dim)  # 차원 변환
                y_pred = model(X_batch)
                val_loss += criterion(y_pred, y_batch).item()

        # 평균 손실 계산
        train_loss /= len(train_loader)
        val_loss /= len(val_loader)

        # 최적의 하이퍼파라미터 업데이트
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_params = {'hidden_dim': hidden_dim, 'lr': lr}

        # 현재 에포크 결과 출력 
        print(f"Params: hidden_dim={hidden_dim}, lr={lr}, Epoch {epoch + 1}/{num_epochs}, "
              f"Train Loss: {train_loss:.4f}, Validation Loss: {val_loss:.4f}")

print("Best Parameters:", best_params)

Params: hidden_dim=64, lr=0.001, Epoch 1/75, Train Loss: 1.1197, Validation Loss: 1.1032
Params: hidden_dim=64, lr=0.001, Epoch 2/75, Train Loss: 1.1040, Validation Loss: 1.0847
Params: hidden_dim=64, lr=0.001, Epoch 3/75, Train Loss: 1.0994, Validation Loss: 1.0861
Params: hidden_dim=64, lr=0.001, Epoch 4/75, Train Loss: 1.0844, Validation Loss: 1.0663
Params: hidden_dim=64, lr=0.001, Epoch 5/75, Train Loss: 1.0643, Validation Loss: 1.0138
Params: hidden_dim=64, lr=0.001, Epoch 6/75, Train Loss: 1.0345, Validation Loss: 0.9617
Params: hidden_dim=64, lr=0.001, Epoch 7/75, Train Loss: 0.9086, Validation Loss: 0.7516
Params: hidden_dim=64, lr=0.001, Epoch 8/75, Train Loss: 0.6920, Validation Loss: 0.6050
Params: hidden_dim=64, lr=0.001, Epoch 9/75, Train Loss: 0.6311, Validation Loss: 0.5427
Params: hidden_dim=64, lr=0.001, Epoch 10/75, Train Loss: 0.5454, Validation Loss: 0.5497
Params: hidden_dim=64, lr=0.001, Epoch 11/75, Train Loss: 0.4960, Validation Loss: 0.6135
Params: hidden_dim=

In [33]:
from sklearn.metrics import classification_report, confusion_matrix

# 테스트 데이터 평가
best_hidden_dim = best_params['hidden_dim']
best_lr = best_params['lr']

# 최적의 하이퍼파라미터로 모델 초기화
model = LSTMModel(input_dim=input_dim, hidden_dim=best_hidden_dim, output_dim=output_dim)
optimizer = optim.Adam(model.parameters(), lr=best_lr)

In [34]:
# 학습된 모델로 테스트 데이터 평가
model.eval()
y_true, y_pred = [], []
test_loader = DataLoader(TensorDataset(torch.tensor(X_test).float(), torch.tensor(y_test).long()), batch_size=4)
with torch.no_grad():
    for X_batch, y_batch in test_loader:
        X_batch = X_batch.view(X_batch.size(0), -1, input_dim)  # 차원 변환
        outputs = model(X_batch)
        _, preds = torch.max(outputs, 1)
        y_true.extend(y_batch.numpy())
        y_pred.extend(preds.numpy())

print(classification_report(y_true, y_pred, target_names=list(labels_map.keys())))
print('-'*100)
print(confusion_matrix(y_true, y_pred))

              precision    recall  f1-score   support

           등       0.00      0.00      0.00         1
         스쿼트       0.00      0.00      0.00         2
         옆구리       0.40      1.00      0.57         2

    accuracy                           0.40         5
   macro avg       0.13      0.33      0.19         5
weighted avg       0.16      0.40      0.23         5

----------------------------------------------------------------------------------------------------
[[0 0 1]
 [0 0 2]
 [0 0 2]]


c:\Users\Admin\miniconda3\envs\myGPU\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Admin\miniconda3\envs\myGPU\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Admin\miniconda3\envs\myGPU\lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [35]:
import torch

# 모델 정의
class SimpleModel(torch.nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = torch.nn.Linear(10, 1)

    def forward(self, x):
        return self.fc(x) 

# 모델 인스턴스 생성 및 학습
# model = SimpleModel()

# 모델 전체 저장
# 모델 스크립팅
scripted_model = torch.jit.script(model)

# 모델 저장
model_path = "C:/vscode/model_scripted.pt"
scripted_model.save(model_path)

'''
torch.save(model, 'model_scripted.pt')

# 모델 전체 불러오기
loaded_model = torch.load('model_scripted.pt')  
loaded_model.eval()  # 평가 모드로 전환
''' 


"\ntorch.save(model, 'model_scripted.pt')\n\n# 모델 전체 불러오기\nloaded_model = torch.load('model_scripted.pt')  \nloaded_model.eval()  # 평가 모드로 전환\n"