In [2]:
import numpy as np

file_path = r'C:\Users\Admin\Documents\GitHub\mini2\data\옆구리\좌표\keypoints_2.npy'
try:
    data = np.load(file_path)
    print(f"Data shape: {data.shape}")
    print(data)  # 데이터 내용 출력
except Exception as e:
    print(f"Error loading file: {e}")


Data shape: (181, 33, 3)
[[[ 0.527192    0.25999653 -0.425035  ]
  [ 0.53474456  0.24414261 -0.40455589]
  [ 0.53810757  0.24471635 -0.40450865]
  ...
  [ 0.48085332  0.93480325  0.23752534]
  [ 0.58927155  0.97663438  0.05493615]
  [ 0.4609918   0.97118866  0.09056696]]

 [[ 0.5271455   0.2599853  -0.42695752]
  [ 0.53474534  0.24414597 -0.40679556]
  [ 0.53810555  0.24472199 -0.40674156]
  ...
  [ 0.48084387  0.93327874  0.23586714]
  [ 0.58922881  0.97662598  0.05347991]
  [ 0.46100292  0.97109067  0.08899807]]

 [[ 0.52713263  0.25999191 -0.42661539]
  [ 0.53474647  0.24416539 -0.40653068]
  [ 0.53810537  0.24474451 -0.40647754]
  ...
  [ 0.48063326  0.9329704   0.23461957]
  [ 0.58912927  0.97655088  0.05260273]
  [ 0.46099758  0.97106946  0.08782019]]

 ...

 [[ 0.52569646  0.25671998 -0.41561729]
  [ 0.53398645  0.24084626 -0.39697036]
  [ 0.53720367  0.24143358 -0.39690918]
  ...
  [ 0.4789106   0.93535137  0.22585292]
  [ 0.58846545  0.97720206  0.047607  ]
  [ 0.46171874  0.9