In [4]:
import numpy as np

file_path = 'C:\\Users\\Admin\\Downloads\\모션저장\\스쿼트\\좌표\\keypoints_1.npy'
try:
    data = np.load(file_path)
    print(f"Data shape: {data.shape}")
    print(data)  # 데이터 내용 출력
except Exception as e:
    print(f"Error loading file: {e}")


Data shape: (59, 33, 3)
[[[ 0.50278533  0.16110109 -0.14114478]
  [ 0.5118255   0.14589748 -0.11305519]
  [ 0.51600397  0.14682774 -0.11305551]
  ...
  [ 0.45179519  0.91469675  0.14990559]
  [ 0.57105303  0.95169538 -0.04309783]
  [ 0.42626056  0.95160067 -0.02285544]]

 [[ 0.50277954  0.16114563 -0.13705371]
  [ 0.51182675  0.14593047 -0.10799805]
  [ 0.51600027  0.14686744 -0.10799944]
  ...
  [ 0.45179743  0.91482437  0.15705745]
  [ 0.571082    0.95177877 -0.03595864]
  [ 0.42627415  0.95174706 -0.01978799]]

 [[ 0.50267231  0.16134119 -0.12945303]
  [ 0.51181269  0.14606121 -0.10029896]
  [ 0.51596588  0.14705153 -0.10029779]
  ...
  [ 0.45177096  0.91482615  0.15958871]
  [ 0.57107955  0.95182866 -0.03162497]
  [ 0.42613158  0.95219094 -0.01879296]]

 ...

 [[ 0.50508231  0.15812905 -0.15446228]
  [ 0.5141269   0.14194173 -0.12571211]
  [ 0.51816714  0.14247559 -0.12570934]
  ...
  [ 0.45226425  0.91150588  0.15552559]
  [ 0.57262909  0.9522121  -0.03428441]
  [ 0.42724317  0.95